global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'uptime-checker'
    static_configs:
      - targets: ['uptime-checker:8000']
    metrics_path: /metrics

  - job_name: 'web-dashboard'
    static_configs:
      - targets: ['web-dashboard:8000']
    metrics_path: /metrics